name: "Photo Proxy"
version: "1.4.0"
slug: "photo-proxy"
description: "A proxy server that serves images from Nextcloud"
url: "https://github.com/joergrs/photo-proxy"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
startup: application
boot: auto
ingress: false
ingress_port: 8181
panel_icon: mdi:image-multiple
ports:
  8181/tcp: 8181
ports_description:
  8181/tcp: "Web interface (not required)"
webui: "http://[HOST]:[PORT:8181]"
options:
  nextcloud_url: ""
  nextcloud_username: ""
  nextcloud_password: ""
  nextcloud_dirs: "Pictures"
  max_image_size: 1920
  jpg_quality: 85
  convert_to_jpg: true
  crop_portrait_to_square: false
  debug_logging: false
schema:
  nextcloud_url: str
  nextcloud_username: str
  nextcloud_password: password
  nextcloud_dirs: str
  max_image_size: int
  jpg_quality: int
  convert_to_jpg: bool
  crop_portrait_to_square: bool
  debug_logging: bool